/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuleTypesIndexRouteImport } from './routes/rule-types/index'
import { Route as PostsAndUsersIndexRouteImport } from './routes/posts-and-users/index'
import { Route as RulesTypes2RouteImport } from './routes/rules/types2'
import { Route as RulesIdRouteImport } from './routes/rules/$id'
import { Route as RuleTypesRuleTypeIdRouteImport } from './routes/rule-types/$ruleTypeId'
import { Route as GovernanceHistoryRouteImport } from './routes/governance/history'
import { Route as GovernanceAccessRouteImport } from './routes/governance/access'
import { Route as CatalogTypeRouteImport } from './routes/catalog/$type'
import { Route as RulesTypesIndexRouteImport } from './routes/rules/types/index'
import { Route as RulesIdIndexRouteImport } from './routes/rules/$id.index'
import { Route as RulesTypesRuleTypeIdRouteImport } from './routes/rules/types/$ruleTypeId'
import { Route as RulesIdSimulateRouteImport } from './routes/rules/$id.simulate'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleTypesIndexRoute = RuleTypesIndexRouteImport.update({
  id: '/rule-types/',
  path: '/rule-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsAndUsersIndexRoute = PostsAndUsersIndexRouteImport.update({
  id: '/posts-and-users/',
  path: '/posts-and-users/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesTypes2Route = RulesTypes2RouteImport.update({
  id: '/rules/types2',
  path: '/rules/types2',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdRoute = RulesIdRouteImport.update({
  id: '/rules/$id',
  path: '/rules/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RuleTypesRuleTypeIdRoute = RuleTypesRuleTypeIdRouteImport.update({
  id: '/rule-types/$ruleTypeId',
  path: '/rule-types/$ruleTypeId',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceHistoryRoute = GovernanceHistoryRouteImport.update({
  id: '/governance/history',
  path: '/governance/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceAccessRoute = GovernanceAccessRouteImport.update({
  id: '/governance/access',
  path: '/governance/access',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogTypeRoute = CatalogTypeRouteImport.update({
  id: '/catalog/$type',
  path: '/catalog/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesTypesIndexRoute = RulesTypesIndexRouteImport.update({
  id: '/rules/types/',
  path: '/rules/types/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdIndexRoute = RulesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RulesIdRoute,
} as any)
const RulesTypesRuleTypeIdRoute = RulesTypesRuleTypeIdRouteImport.update({
  id: '/rules/types/$ruleTypeId',
  path: '/rules/types/$ruleTypeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesIdSimulateRoute = RulesIdSimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => RulesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog/$type': typeof CatalogTypeRoute
  '/governance/access': typeof GovernanceAccessRoute
  '/governance/history': typeof GovernanceHistoryRoute
  '/rule-types/$ruleTypeId': typeof RuleTypesRuleTypeIdRoute
  '/rules/$id': typeof RulesIdRouteWithChildren
  '/rules/types2': typeof RulesTypes2Route
  '/posts-and-users/': typeof PostsAndUsersIndexRoute
  '/rule-types/': typeof RuleTypesIndexRoute
  '/rules/$id/simulate': typeof RulesIdSimulateRoute
  '/rules/types/$ruleTypeId': typeof RulesTypesRuleTypeIdRoute
  '/rules/$id/': typeof RulesIdIndexRoute
  '/rules/types/': typeof RulesTypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog/$type': typeof CatalogTypeRoute
  '/governance/access': typeof GovernanceAccessRoute
  '/governance/history': typeof GovernanceHistoryRoute
  '/rule-types/$ruleTypeId': typeof RuleTypesRuleTypeIdRoute
  '/rules/types2': typeof RulesTypes2Route
  '/posts-and-users': typeof PostsAndUsersIndexRoute
  '/rule-types': typeof RuleTypesIndexRoute
  '/rules/$id/simulate': typeof RulesIdSimulateRoute
  '/rules/types/$ruleTypeId': typeof RulesTypesRuleTypeIdRoute
  '/rules/$id': typeof RulesIdIndexRoute
  '/rules/types': typeof RulesTypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog/$type': typeof CatalogTypeRoute
  '/governance/access': typeof GovernanceAccessRoute
  '/governance/history': typeof GovernanceHistoryRoute
  '/rule-types/$ruleTypeId': typeof RuleTypesRuleTypeIdRoute
  '/rules/$id': typeof RulesIdRouteWithChildren
  '/rules/types2': typeof RulesTypes2Route
  '/posts-and-users/': typeof PostsAndUsersIndexRoute
  '/rule-types/': typeof RuleTypesIndexRoute
  '/rules/$id/simulate': typeof RulesIdSimulateRoute
  '/rules/types/$ruleTypeId': typeof RulesTypesRuleTypeIdRoute
  '/rules/$id/': typeof RulesIdIndexRoute
  '/rules/types/': typeof RulesTypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog/$type'
    | '/governance/access'
    | '/governance/history'
    | '/rule-types/$ruleTypeId'
    | '/rules/$id'
    | '/rules/types2'
    | '/posts-and-users/'
    | '/rule-types/'
    | '/rules/$id/simulate'
    | '/rules/types/$ruleTypeId'
    | '/rules/$id/'
    | '/rules/types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog/$type'
    | '/governance/access'
    | '/governance/history'
    | '/rule-types/$ruleTypeId'
    | '/rules/types2'
    | '/posts-and-users'
    | '/rule-types'
    | '/rules/$id/simulate'
    | '/rules/types/$ruleTypeId'
    | '/rules/$id'
    | '/rules/types'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog/$type'
    | '/governance/access'
    | '/governance/history'
    | '/rule-types/$ruleTypeId'
    | '/rules/$id'
    | '/rules/types2'
    | '/posts-and-users/'
    | '/rule-types/'
    | '/rules/$id/simulate'
    | '/rules/types/$ruleTypeId'
    | '/rules/$id/'
    | '/rules/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogTypeRoute: typeof CatalogTypeRoute
  GovernanceAccessRoute: typeof GovernanceAccessRoute
  GovernanceHistoryRoute: typeof GovernanceHistoryRoute
  RuleTypesRuleTypeIdRoute: typeof RuleTypesRuleTypeIdRoute
  RulesIdRoute: typeof RulesIdRouteWithChildren
  RulesTypes2Route: typeof RulesTypes2Route
  PostsAndUsersIndexRoute: typeof PostsAndUsersIndexRoute
  RuleTypesIndexRoute: typeof RuleTypesIndexRoute
  RulesTypesRuleTypeIdRoute: typeof RulesTypesRuleTypeIdRoute
  RulesTypesIndexRoute: typeof RulesTypesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-types/': {
      id: '/rule-types/'
      path: '/rule-types'
      fullPath: '/rule-types/'
      preLoaderRoute: typeof RuleTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts-and-users/': {
      id: '/posts-and-users/'
      path: '/posts-and-users'
      fullPath: '/posts-and-users/'
      preLoaderRoute: typeof PostsAndUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/types2': {
      id: '/rules/types2'
      path: '/rules/types2'
      fullPath: '/rules/types2'
      preLoaderRoute: typeof RulesTypes2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id': {
      id: '/rules/$id'
      path: '/rules/$id'
      fullPath: '/rules/$id'
      preLoaderRoute: typeof RulesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rule-types/$ruleTypeId': {
      id: '/rule-types/$ruleTypeId'
      path: '/rule-types/$ruleTypeId'
      fullPath: '/rule-types/$ruleTypeId'
      preLoaderRoute: typeof RuleTypesRuleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/history': {
      id: '/governance/history'
      path: '/governance/history'
      fullPath: '/governance/history'
      preLoaderRoute: typeof GovernanceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/access': {
      id: '/governance/access'
      path: '/governance/access'
      fullPath: '/governance/access'
      preLoaderRoute: typeof GovernanceAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$type': {
      id: '/catalog/$type'
      path: '/catalog/$type'
      fullPath: '/catalog/$type'
      preLoaderRoute: typeof CatalogTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/types/': {
      id: '/rules/types/'
      path: '/rules/types'
      fullPath: '/rules/types/'
      preLoaderRoute: typeof RulesTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id/': {
      id: '/rules/$id/'
      path: '/'
      fullPath: '/rules/$id/'
      preLoaderRoute: typeof RulesIdIndexRouteImport
      parentRoute: typeof RulesIdRoute
    }
    '/rules/types/$ruleTypeId': {
      id: '/rules/types/$ruleTypeId'
      path: '/rules/types/$ruleTypeId'
      fullPath: '/rules/types/$ruleTypeId'
      preLoaderRoute: typeof RulesTypesRuleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/$id/simulate': {
      id: '/rules/$id/simulate'
      path: '/simulate'
      fullPath: '/rules/$id/simulate'
      preLoaderRoute: typeof RulesIdSimulateRouteImport
      parentRoute: typeof RulesIdRoute
    }
  }
}

interface RulesIdRouteChildren {
  RulesIdSimulateRoute: typeof RulesIdSimulateRoute
  RulesIdIndexRoute: typeof RulesIdIndexRoute
}

const RulesIdRouteChildren: RulesIdRouteChildren = {
  RulesIdSimulateRoute: RulesIdSimulateRoute,
  RulesIdIndexRoute: RulesIdIndexRoute,
}

const RulesIdRouteWithChildren =
  RulesIdRoute._addFileChildren(RulesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogTypeRoute: CatalogTypeRoute,
  GovernanceAccessRoute: GovernanceAccessRoute,
  GovernanceHistoryRoute: GovernanceHistoryRoute,
  RuleTypesRuleTypeIdRoute: RuleTypesRuleTypeIdRoute,
  RulesIdRoute: RulesIdRouteWithChildren,
  RulesTypes2Route: RulesTypes2Route,
  PostsAndUsersIndexRoute: PostsAndUsersIndexRoute,
  RuleTypesIndexRoute: RuleTypesIndexRoute,
  RulesTypesRuleTypeIdRoute: RulesTypesRuleTypeIdRoute,
  RulesTypesIndexRoute: RulesTypesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
